In [7]:
import json

dic_points = {}
  
# Opening JSON file
f = open(r"C:\Users\jorge\Desktop\all_via_region_data.json")

# returns JSON object as 
# a dictionary
data = json.load(f)

dic_points = {}
ids_images = []

# Iterating through the json
# list
for key, value in data.items():
    regions = value["regions"]
    filename = value["filename"]
    file = filename[-26:]
    for it in regions:
        it = it["shape_attributes"]
        px = it["all_points_x"]
        py = it["all_points_y"]
        poly = [(x + 0.5, y + 0.5) for x, y in zip(px, py)]
        # poly = [p for x in poly for p in x]
        # poly = np.array(poly)

        dic_points[file] = [poly]
        ids_images.append(file[4:22])

# Closing file
f.close()

In [ ]:
import cv2
import numpy as np
import csv, os, shutil

path_source = r'C:/Users/jorge/Desktop/IMAGES_MASKS/Images/'
path_dest = r'C:/Users/jorge/Desktop/IMAGES_MASKS/Masks/'

with open(r'C:\Users\jorge\Desktop\GalaxyZoo1_DR_table2.csv', newline='') as File:
    reader = csv.reader(File)
    for row in reader:
        if row[0] in ids_images:
            key = 'Dr7_' + row[0] + '.jpg'
            file_source = path_source + key
            if os.path.isfile(file_source):
                im = cv2.imread(file_source)
                pts = np.array(dic_points[key], np.int32)
                mask = np.zeros((im.shape[0], im.shape[1], im.shape[2]), np.float64)
                
                color = (0, 0, 0)
                if int(row[13]) == 1:
                    color = (128, 128, 128)
                elif int(row[14]) == 1:
                    color = (100, 100, 100)
                elif int(row[15]) == 1:
                    color = (194, 194, 194)

                for i in range(im.shape[0]):
                    for j in range(im.shape[1]):
                        if cv2.pointPolygonTest(pts, [j,i], False) != -1.0:
                            mask[i,j,:] = color
                
                file_dest = path_dest + key
                cv2.imwrite(file_dest, mask)

In [1]:
import cv2, os

folder = r'C:/Users/jorge/Desktop/IMAGES_MASKS/Masks/'
aux = 0

contenido = os.listdir(folder)
images = []
for fichero in contenido:
    path = os.path.join(folder, fichero)
    if os.path.isfile(path) and fichero.endswith('.jpg'):
        images.append(fichero)
        im = cv2.imread(path)
        aux = 0
        print(im.shape[0], ' ', im.shape[1], ' ', im.shape[2])
        for i in range(im.shape[0]):
            for j in range(im.shape[1]):
                if im[i,j,0] == 100 and im[i,j,1] == 100 and im[i,j,2] == 100:
                    aux += 1
        print(aux)
        
print('Images leidas: ', len(images))

256   256   3
438
256   256   3
396
256   256   3
844
256   256   3
620
256   256   3
1517
256   256   3
0
256   256   3
0
256   256   3
0
256   256   3
0
256   256   3
0
256   256   3
0
256   256   3
0
256   256   3
0
256   256   3
0
256   256   3
0
Images leidas:  15


In [6]:
import cv2
im = cv2.imread(r'C:\Users\jorge\Desktop\IMAGES_MASKS\Masks\Dr7_587725074455265474.jpg')
print(im.shape)
aux = 0

for i in range(im.shape[0]):
    for j in range(im.shape[1]):
        if im[i,j,0] != 100 and im[i,j,1] != 100 and im[i,j,2] != 100:
            if im[i,j,0] != 0 and im[i,j,1] != 0 and im[i,j,2] != 0:
                print(im[i,j,:])
                aux += 1
                
                '''
                if im[i,j,0] == 128 and im[i,j,1] == 128 and im[i,j,2] == 128:
                    im[i,j,:] = (255, 0, 0)
                    aux += 1
                    
                if im[i,j,0] == 194 and im[i,j,1] == 194 and im[i,j,2] == 194:
                    im[i,j,:] = (0, 255, 0)
                    aux += 1
                '''
                
                

cv2.imwrite(r'C:\Users\jorge\Desktop\IMAGES_MASKS\Masks\Dr7_587725074455265474.jpg', im)
print(aux)

(256, 256, 3)
[3 3 3]
[5 5 5]
[4 4 4]
[4 4 4]
[3 3 3]
[1 1 1]
[1 1 1]
[2 2 2]
[3 3 3]
[1 1 1]
[1 1 1]
[1 1 1]
[2 2 2]
[3 3 3]
[1 1 1]
[4 4 4]
[1 1 1]
[4 4 4]
[5 5 5]
[2 2 2]
[101 101 101]
[103 103 103]
[98 98 98]
[102 102 102]
[98 98 98]
[101 101 101]
[98 98 98]
[99 99 99]
[99 99 99]
[1 1 1]
[2 2 2]
[4 4 4]
[1 1 1]
[3 3 3]
[3 3 3]
[4 4 4]
[1 1 1]
[1 1 1]
[3 3 3]
[1 1 1]
[103 103 103]
[97 97 97]
[103 103 103]
[97 97 97]
[99 99 99]
[102 102 102]
[99 99 99]
[98 98 98]
[101 101 101]
[99 99 99]
[103 103 103]
[102 102 102]
[99 99 99]
[95 95 95]
[1 1 1]
[1 1 1]
[3 3 3]
[5 5 5]
[5 5 5]
[1 1 1]
[1 1 1]
[3 3 3]
[2 2 2]
[101 101 101]
[101 101 101]
[101 101 101]
[101 101 101]
[101 101 101]
[98 98 98]
[103 103 103]
[99 99 99]
[101 101 101]
[96 96 96]
[102 102 102]
[101 101 101]
[102 102 102]
[1 1 1]
[1 1 1]
[3 3 3]
[4 4 4]
[3 3 3]
[3 3 3]
[2 2 2]
[3 3 3]
[1 1 1]
[97 97 97]
[101 101 101]
[101 101 101]
[95 95 95]
[105 105 105]
[101 101 101]
[101 101 101]
[95 95 95]
[98 98 98]
[101 101 101]
[99 99 99]